### ISSUE TITLE
Custom Task NER with Huggingface

### ISSUE THREAD

**Issue by Mrs-Hudson** [hitz-zentroa/GoLLIE#13]
Hi

I want to run this [notebook](https://github.com/hitz-zentroa/GoLLIE/blob/main/notebooks/Create%20Custom%20Task.ipynb). Is it possible to do so with the hugginface model instead of using the local_model method from the GoLLIE repo's source code?

**Comment by ikergarcia1996** [comment]
Hello @Mrs-Hudson 

Yes, you can load the huggingface model without the GoLLIE source code this way:
```python
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("HiTZ/GoLLIE-7B")
model = AutoModelForCausalLM.from_pretrained("HiTZ/GoLLIE-7B", trust_remote_code=True, torch_dtype=torch.bfloat16)
model.to("cuda")
```
