### ISSUE TITLE
How to construct Diann cropus 

### ISSUE THREAD

**Issue by TuRan-sino** [hitz-zentroa/GoLLIE#22]
I'm trying to download the Diann corpus from the link you provided [DIANN](http://nlp.uned.es/diann/). 
However, I couldn't find any download link on that website. Therefore, I searched on GitHub and downloaded the Diann corpus provided by [gildofabregat/DIANN-IBEREVAL-2018](https://github.com/gildofabregat/DIANN-IBEREVAL-2018/tree/master/DIANN_CORPUS)
After unzipping the file, I found that the files were all .txt files instead of .tsv files. Did I download the wrong dataset, or is there some preprocessing script that I haven't used?

**Comment by ikergarcia1996** [comment]
Hello @TuRan-sino 

You can obtain the .tsv file by processing the .txt files, which are annotated with HTML tags. To save you the hassle, here is the preprocessed dataset.

[diann.zip](https://github.com/user-attachments/files/15873494/diann.zip)

**Comment by TuRan-sino** [comment]
Thank you for your help
