### ISSUE TITLE
OOM 

### ISSUE THREAD

**Issue by jmanhype** [hitz-zentroa/GoLLIE#3]
checkpoint keep getting killed. seems like it neeeds 33 gb of memory and its being loaded by fp32. help

**Comment by jmanhype** [comment]
im doing low cpu mem its loading 66 percent and then getting killed
now sure if i need to shard or what?

**Comment by ikergarcia1996** [comment]
Hi @jmanhype!

Can you provide more information? Which configuration file and model are you attempting to run?

**Comment by jmanhype** [comment]
Im loading the pre trained model 7b

**Comment by jmanhype** [comment]
Using the baseline 7b config file

**Comment by osainz59** [comment]
Hi @jmanhype !

The baseline in this repository refers to the baseline with which we compare in the paper. If you want to try the 7B model you should use this config: [configs/model_configs/eval/CoLLIE-7B_CodeLLaMA.yaml](configs/model_configs/eval/CoLLIE-7B_CodeLLaMA.yaml)

**Comment by ikergarcia1996** [comment]
How much RAM does your machine have?
Are you using the latest HuggingFace transformers version?
Are you using our load_model function or the AutoModelForCausalLM.from_pretrained function?

We uploaded the weights in float32 to ensure compatibility with devices that do not support bfloat16 (e.g., V100 GPUs). I will attempt to replicate the issue on a 32GB RAM machine and get back to you in a few hours. If necessary, we will upload the bf16 weights.

**Comment by jmanhype** [comment]
Device name	DESKTOP-06OLKHE
Processor	Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz   3.60 GHz
Installed RAM	32.0 GB (31.9 GB usable)
Device ID	9B8CB989-464F-4937-B0E5-762B06509499
Product ID	00325-81789-21676-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display



what if you did that and uploaded sharded version or would that not fix it ? 

side note i went from it getting killed straight away to it loadig 2/3 checkpoints then getting killed using the -low-cpu-memory method

**Comment by jmanhype** [comment]
I have  a gtx 2080 super 8gb

**Comment by jmanhype** [comment]
Lmk what you think
